version: '3.8'

services:

  db:
    container_name: postgress
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product
    ports:
      - "8080:8080"
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root123
    ports:
      - "15432:80"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
